version: "3"
services:
  #  volumes:
  #    database_volumes:
  #      external: true
  #      name: [ volume-name ]

  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_DATABASE: userdb
      #      MYSQL_USER: user
      #      MYSQL_PASSWORD: userpwd
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpwd
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    expose:
      - "3303"
    volumes:
      - ./backups:/home/backups
    ports:
      - "3303:3306"
    restart: always

  application:
    container_name: application
    env_file:
      .env
    image: 042973332120.dkr.ecr.ap-northeast-2.amazonaws.com/pocket-pt:latest
    depends_on:
      - mysql-db
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always

#  chat-db:
#    container_name: chat-db
#    image: mysql
#    environment:
#      MYSQL_DATABASE: chatdb
#      #      MYSQL_USER: user
#      #      MYSQL_PASSWORD: userpwd
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: rootpwd
#    command:
#      - --default-authentication-plugin=mysql_native_password
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#      - --skip-character-set-client-handshake
#    expose:
#      - "3303"
#    volumes:
#      - ./backups:/home/backups
#    ports:
#      - "3303:3306"
#    restart: always
#
#  chat-server:
#    container_name: chat-server
#    build: ./springboot-chat-server
#    depends_on:
#      - chat-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/chatdb?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: rootpwd
#    restart: always
